const houseTypeParams = [
  {
    id: "售价降",
    name: "售价降",
    select: false
  },
  {
    id: "售价涨",
    name: "售价涨",
    select: false
  },
  {
    id: "售价修改",
    name: "售价修改",
    select: false
  },
  {
    id: "租价降",
    name: "租价降",
    select: false
  },
  {
    id: "租价涨",
    name: "租价涨",
    select: false
  },
  {
    id: "封盘",
    name: "封盘",
    select: false
  },
  {
    id: "特盘",
    name: "特盘",
    select: false
  },
  {
    id: "私盘",
    name: "私盘",
    select: false
  },
  {
    id: "私盘",
    name: "私盘",
    select: false
  },
  {
    id: "状态修改",
    name: "状态修改",
    select: false
  },
  {
    id: "有效",
    name: "有效",
    select: false
  },
  {
    id: "预定",
    name: "预定",
    select: false
  },
  {
    id: "我售",
    name: "我售",
    select: false
  },
  {
    id: "已售",
    name: "已售",
    select: false
  },
  {
    id: "我租",
    name: "我租",
    select: false
  },
  {
    id: "已租",
    name: "已租",
    select: false
  },
  {
    id: "暂缓",
    name: "暂缓",
    select: false
  },
  {
    id: "未知",
    name: "未知",
    select: false
  },
  {
    id: "无效",
    name: "无效",
    select: false
  }
];
const houseTradeParams = [
  {
    id: "1",
    name: "出售",
    select: false
  },
  {
    id: "2",
    name: "出租",
    select: false
  },
  {
    id: "3",
    name: "租售",
    select: false
  }
];

const contractColumn = [
  {
    id:"2019121901",
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'√',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"201912190222",
    type:'',
    width:'100',
    ref:'',
    prop:'createTime',
    label:'提交日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121902",
    type:'',
    width:'80',
    ref:'',
    prop:'contractCode',
    label:'合同编号',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },

  {
    id:"2019121903",
    type:'',
    width:'65',
    ref:'',
    prop:'num',
    label:'自定号',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },

  {
    id:"2019121904",
    type:'',
    width:'100',
    ref:'',
    prop:'businessType',
    label:'业类',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121905",
    type:'',
    width:'200',
    ref:'',
    prop:'roomAddress',
    label:'房源/新房地址',
    sortable:true,
    show:true,
    fixed:false,
    align:'left',
  },
  {
    id:"2019121906",
    type:'',
    width:'80',
    ref:'',
    prop:'roomNum',
    label:'房源/项目编号',
    sortable:true,
    show:false,
    fixed:false,
    align:'left',
  },
  {
    id:"2019121907",
    type:'',
    width:'90',
    ref:'',
    prop:'businessNum',
    label:'认购/委托编号',
    sortable:true,
    show:false,
    fixed:false,
    align:'left',
  },
  {
    id:"201912198",
    type:'',
    width:'100',
    ref:'',
    prop:'price',
    label:'售价',
    sortable:true,
    show:true,
    fixed:false,
    align:'right',
  },
  {
    id:"201912109",
    type:'',
    width:'100',
    ref:'',
    prop:'unitPrice',
    label:'单价',
    sortable:true,
    show:false,
    fixed:false,
    align:'right',
  },
  {
    id:"2019121910",
    type:'',
    width:'100',
    ref:'',
    prop:'realEstateNum',
    label:'房产证号',
    sortable:true,
    show:false,
    fixed:false,
    align:'right',
  },

  {
    id:"2019121911",
    type:'',
    width:'90',
    ref:'',
    prop:'roomArea',
    label:'面积',
    sortable:true,
    show:true,
    fixed:false,
    align:'right',
  },
  {
    id:"2019121912",
    type:'',
    width:'100',
    ref:'',
    prop:'contractDate',
    label:'签约日',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },

  {
    id:"2019121913",
    type:'',
    width:'80',
    ref:'',
    prop:'roomUseId',
    label:'用途',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121914",
    type:'',
    width:'140',
    ref:'',
    prop:'contractEmpId',
    label:'签约人员',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121915",
    type:'',
    width:'140',
    ref:'',
    prop:'contractLeaderId',
    label:'签约经理',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },

  {
    id:"2019121916",
    type:'',
    width:'50',
    ref:'',
    prop:'stateId',
    label:'状态',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121917",
    type:'',
    width:'100',
    ref:'',
    prop:'ownerName',
    label:'业主姓名/开发商',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121918",
    type:'',
    width:'100',
    ref:'',
    prop:'ownerPhone',
    label:'手机',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121919",
    type:'',
    width:'200',
    ref:'',
    prop:'ownerAddress',
    label:'联系/销售地址',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121920",
    type:'',
    width:'200',
    ref:'',
    prop:'ownerId',
    label:'身份证号',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121921",
    type:'',
    width:'100',
    ref:'',
    prop:'customerName',
    label:'客户姓名',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121922",
    type:'',
    width:'100',
    ref:'',
    prop:'customerPhone',
    label:'手机',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121923",
    type:'',
    width:'80',
    ref:'',
    prop:'customerCode',
    label:'客户编号',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121924",
    type:'',
    width:'200',
    ref:'',
    prop:'customerAddress',
    label:'联系地址',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121925",
    type:'',
    width:'200',
    ref:'',
    prop:'customerIdCard',
    label:'身份证号',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121926",
    type:'',
    width:'110',
    ref:'',
    prop:'customerIdCard',
    label:'佣金类型',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121927",
    type:'',
    width:'110',
    ref:'',
    prop:'customerIdCard',
    label:'佣金模式',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121928",
    type:'',
    width:'80',
    ref:'',
    prop:'finishSalary',
    label:'结佣状态',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121929",
    type:'',
    width:'100',
    ref:'',
    prop:'finishSalaryDate',
    label:'结佣日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121930",
    type:'',
    width:'80',
    ref:'',
    prop:'finishEnd',
    label:'结盘状态',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121931",
    type:'',
    width:'100',
    ref:'',
    prop:'finishEndDate',
    label:'结盘日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },


];
const contractCommission = [
  {
    id: "2019121901",
    type: "selection1",
    width: "30",
    ref: "multipleTable1",
    prop: "check",
    label: "√",
    sortable: false,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121902",
    type: "",
    width: "160",
    ref: "",
    prop: "userName",
    label: "业绩人",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121903",
    type: "",
    width: "50",
    ref: "",
    prop: "category",
    label: "业类",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121904",
    type: "",
    width: "70",
    ref: "",
    prop: "proportion",
    label: "比例",
    sortable: true,
    show: true,
    fixed: false,
    align: "right"
  },
  {
    id: "2019121905",
    type: "",
    width: "90",
    ref: "",
    prop: "receivable",
    label: "应收业绩",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121906",
    type: "",
    width: "90",
    ref: "",
    prop: "receipts",
    label: "实收业绩",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121907",
    type: "",
    width: "90",
    ref: "",
    prop: "patternLevel",
    label: "模式",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121908",
    type: "",
    width: "90",
    ref: "",
    prop: "bonus",
    label: "应计提金",
    sortable: true,
    show: true,
    fixed: false,
    align: "right"
  },
  {
    id: "20191219009",
    type: "",
    width: "90",
    ref: "",
    prop: "deduct",
    label: "特殊扣除",
    sortable: true,
    show: true,
    fixed: false,
    align: "right"
  },
  {
    id: "2019121910",
    type: "",
    width: "50",
    ref: "",
    prop: "type",
    label: "方式",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121911",
    type: "",
    width: "85",
    ref: "",
    prop: "balanceTime",
    label: "结算年月",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121912",
    type: "",
    width: "70",
    ref: "",
    prop: "firstBalance",
    label: "首次结算",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121913",
    type: "",
    width: "70",
    ref: "",
    prop: "totilBalance",
    label: "总补结算",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121914",
    type: "",
    width: "60",
    ref: "",
    prop: "isCalculateSalary",
    label: "计工资",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  }
];
const contractPerson = [
  {
    id: "2019121901",
    type: "selection2",
    width: "30",
    ref: "multipleTable2",
    prop: "check",
    label: "√",
    sortable: false,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121902",
    type: "",
    width: "160",
    ref: "",
    prop: "userName",
    label: "被同步人",
    sortable: false,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121903",
    type: "",
    width: "50",
    ref: "",
    prop: "category",
    label: "业类",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  
  {
    id: "2019121904",
    type: "",
    width: "70",
    ref: "",
    prop: "proportion",
    label: "比例",
    sortable: true,
    show: true,
    fixed: false,
    align: "right"
  },
  {
    id: "2019121905",
    type: "",
    width: "90",
    ref: "",
    prop: "receivable",
    label: "应收业绩",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121906",
    type: "",
    width: "90",
    ref: "",
    prop: "receipts",
    label: "实收业绩",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121907",
    type: "",
    width: "90",
    ref: "",
    prop: "patternLevel",
    label: "模式",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121908",
    type: "",
    width: "90",
    ref: "",
    prop: "bonus",
    label: "应计提金",
    sortable: true,
    show: true,
    fixed: false,
    align: "right"
  },
  {
    id: "20191219009",
    type: "",
    width: "90",
    ref: "",
    prop: "deduct",
    label: "特殊扣除",
    sortable: true,
    show: true,
    fixed: false,
    align: "right"
  },
  {
    id: "2019121910",
    type: "",
    width: "50",
    ref: "",
    prop: "type",
    label: "方式",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121911",
    type: "",
    width: "85",
    ref: "",
    prop: "balanceTime",
    label: "结算年月",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121912",
    type: "",
    width: "70",
    ref: "",
    prop: "firstBalance",
    label: "首次结算",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121913",
    type: "",
    width: "70",
    ref: "",
    prop: "totilBalance",
    label: "总补结算",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  },
  {
    id: "2019121914",
    type: "",
    width: "60",
    ref: "",
    prop: "isCalculateSalary",
    label: "计工资",
    sortable: true,
    show: true,
    fixed: false,
    align: "center"
  }
];
const contractProgress = [
  {
    id:"2019121901",
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'√',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121902",
    type:'',
    width:'80',
    ref:'',
    prop:'contractDate',
    label:'签约日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121903",
    type:'',
    width:'80',
    ref:'',
    prop:'contractEmpId',
    label:'签约人员',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121904",
    type:'',
    width:'70',
    ref:'',
    prop:'businessType',
    label:'业类',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121905",
    type:'',
    width:'80',
    ref:'',
    prop:'roomNum',
    label:'房源编号',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121906",
    type:'',
    width:'150',
    ref:'',
    prop:'roomAddress',
    label:'房源地址',
    sortable:true,
    show:true,
    fixed:false,
    align:'left',
  },
  {
    id:"2019121907",
    type:'',
    width:'80',
    ref:'',
    prop:'empId',
    label:'负责人',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121908",
    type:'',
    width:'80',
    ref:'',
    prop:'contractPrice',
    label:'合同价格',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121909",
    type:'',
    width:'120',
    ref:'',
    prop:'contractNum',
    label:'商品房合同编号',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121910",
    type:'',
    width:'80',
    ref:'',
    prop:'payWayId',
    label:'付款方式',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },

  {
    id:"2019121911",
    type:'',
    width:'80',
    ref:'',
    prop:'payInAdvance',
    label:'首付款',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121912",
    type:'',
    width:'80',
    ref:'',
    prop:'businessLoan',
    label:'商贷',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121913",
    type:'',
    width:'80',
    ref:'',
    prop:'governmentLoan',
    label:'公贷',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121914",
    type:'',
    width:'80',
    ref:'',
    prop:'registration',
    label:'备案登记',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121915",
    type:'',
    width:'80',
    ref:'',
    prop:'faceSignDate',
    label:'面签进度',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121916",
    type:'',
    width:'80',
    ref:'',
    prop:'loanDate',
    label:'放款进度',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121917",
    type:'',
    width:'80',
    ref:'',
    prop:'propertyDate',
    label:'房屋验收',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121918",
    type:'',
    width:'80',
    ref:'',
    prop:'management',
    label:'产权办理',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  }
];
const shouldFinanceColumn = [
  {
    id:"2019121901",
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'√',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121904",
    type:'',
    width:'180',
    ref:'',
    prop:'roomAddress',
    label:'房源地址',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121905",
    type:'',
    width:'180',
    ref:'',
    prop:'businessType1',
    label:'业类',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121907",
    type:'',
    width:'80',
    ref:'',
    prop:'sourceGetId',
    label:'收付方',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121908",
    type:'',
    width:'90',
    ref:'',
    prop:'sourceGetAmount',
    label:'金额',
    sortable:true,
    show:true,
    fixed:false,
    align:'right',
  },

  {
    id:"2019121902",
    type:'',
    width:'80',
    ref:'',
    prop:'getPayDate',
    label:'收付日期',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },

  {
    id:"2019121911",
    type:'',
    width:'200',
    ref:'',
    prop:'remark',
    label:'备注',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121912",
    type:'',
    width:'100',
    ref:'',
    prop:'finishSalaryDate',
    label:'结佣日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121913",
    type:'',
    width:'100',
    ref:'',
    prop:'finishEndDate',
    label:'结盘日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  }
];
const realFinanceColumn = [
  {
    id:"2019121901",
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'√',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121904",
    type:'',
    width:'180',
    ref:'',
    prop:'roomAddress',
    label:'房源地址',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121905",
    type:'',
    width:'180',
    ref:'',
    prop:'businessType1',
    label:'业类',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121907",
    type:'',
    width:'80',
    ref:'',
    prop:'sourceGetId',
    label:'收付方',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121908",
    type:'',
    width:'90',
    ref:'',
    prop:'sourceGetAmount',
    label:'金额',
    sortable:true,
    show:true,
    fixed:false,
    align:'right',
  },
  {
    id:"20191219102",
    type:'',
    width:'80',
    ref:'',
    prop:'sourceGetType',
    label:'方式',
    sortable:true,
    show:true,
    fixed:false,
    align:'right',
  },
  {
    id:"2019121902",
    type:'',
    width:'100',
    ref:'',
    prop:'getPayDate',
    label:'收付日期',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"20191219104",
    type:'',
    width:'140',
    ref:'',
    prop:'managerId',
    label:'财务人',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121911",
    type:'',
    width:'200',
    ref:'',
    prop:'remark',
    label:'备注',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121912",
    type:'',
    width:'100',
    ref:'',
    prop:'finishSalaryDate',
    label:'结佣日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121913",
    type:'',
    width:'100',
    ref:'',
    prop:'finishEndDate',
    label:'结盘日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  }
];
export const contractParam = {
  contractPerson: contractPerson,
  contractCommission: contractCommission,
  contractColumn: contractColumn,
  houseTradeParams: houseTradeParams,
  houseTypeParams: houseTypeParams,
  contractProgress:contractProgress,
  shouldFinanceColumn:shouldFinanceColumn,
  realFinanceColumn:realFinanceColumn,
};
