const jobColumn = [
  {
    id:20190101,
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'',
    align:'center',
    sortable:false,
    show:true,
    fixed:false
  },
  {
    id:20190102,
    type:'',
    width:'80',
    ref:'',
    prop:'num',
    label:'编号',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190103,
    type:'',
    width:'80',
    ref:'',
    prop:'name',
    label:'职位名称',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190106,
    type:'',
    width:'80',
    ref:'',
    prop:'doManage',
    label:'做管理',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190105,
    type:'',
    width:'120',
    ref:'',
    prop:'doBusiness',
    label:'挂房客及统计管理',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190107,
    type:'',
    width:'200',
    ref:'',
    prop:'remark',
    label:'备注',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190108,
    type:'',
    width:'30',
    ref:'',
    prop:'check1',
    label:'√',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190109,
    type:'',
    width:'100',
    ref:'',
    prop:'time',
    label:'账套年月',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },

  {
    id:20190110,
    type:'',
    width:'80',
    ref:'',
    prop:'accountNum',
    label:'账套人数',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190111,
    type:'',
    width:'100',
    ref:'',
    prop:'salaryNum',
    label:'底薪',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },

  {
    id:20190112,
    type:'',
    width:'100',
    ref:'',
    prop:'priceCom1',
    label:'保险(公司)',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190113,
    type:'',
    width:'100',
    ref:'',
    prop:'pricePer1',
    label:'保险(个人)',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190114,
    type:'',
    width:'100',
    ref:'',
    prop:'priceCom2',
    label:'公积金(公司)',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190115,
    type:'',
    width:'100',
    ref:'',
    prop:'pricePer2',
    label:'公积金(个人)',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190116,
    type:'',
    width:'50',
    ref:'',
    prop:'attendanceNum1',
    label:'请假',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190117,
    type:'',
    width:'50',
    ref:'',
    prop:'attendanceNum2',
    label:'旷工',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190118,
    type:'',
    width:'50',
    ref:'',
    prop:'attendanceNum3',
    label:'缺卡',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190119,
    type:'',
    width:'50',
    ref:'',
    prop:'attendanceNum4',
    label:'时次',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  
  {
    id:20190121,
    type:'',
    width:'50',
    ref:'',
    prop:'attendanceNum6',
    label:'早退',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  },
  {
    id:20190120,
    type:'',
    width:'50',
    ref:'',
    prop:'attendanceNum5',
    label:'迟到',
    align:'center',
    sortable:true,
    show:false,
    fixed:false
  }
];

export const jobParam = {
  jobColumn: jobColumn,
}
