//房， 厅  ，阳台
let houseArr = [{id:'-1',name:' '}];
for(let i = 0 ; i < 11 ; i ++){
  houseArr.push({id:i,name:i});
}
// 房产证
const premisesArr = [
    {id:1,name:"1人"},
    {id:2,name:"2人"},
    {id:3,name:"3人"},
    {id:4,name:"多人"},
];

let date = new Date();
let arr = [];
let year = date.getFullYear();
year = year + 2;
for(let i = year ; i > 1939 ; i--){
  let obj = {
    id:i,
    name:i,
  };
  arr.push(obj);
}
arr = arr.concat([
  {
    id:'2000年以后',name:'2000年以后'
  },
  {
    id:'90年代',name:'90年代'
  },
  {
    id:'80年代',name:'80年代'
  },
  {
    id:'70年代',name:'70年代'
  },
  {
    id:'60年代',name:'60年代'
  },
  {
    id:'50年代',name:'50年代'
  },
])

//建年
const yearArr =  arr;

//售价单位
const salePriceParams = [
  {
    id:'万元',name:"万元",
  },

];
const rentPriceParams = [
  {
    id:'元/月',name:"元/月",
  },
  {
    id:'万元/月',name:"万元/月",
  },
  {
    id:'元/天',name:"元/天",
  },
  {
    id:'万元/天',name:"万元/天",
  },
  
];

const houseParams1 = [
  {
    id:'-1',name:'全部',
  },
  {
    id:'1',name:'新房',
  },
  {
    id: '2', name: '租售',
  }

];

const houseShapeType = [
  
  {
    id:'1',name:'1房',
  },
  {
    id: '2', name: '2房',
  },
  {
    id: '3', name: '3房',
  },
  {
    id: '4', name: '4房',
  },
  {
    id: '5', name: '5房',
  },
  {
    id: '6', name: '单间+1房',
  },
  {
    id: '7', name: '1~2房',
  },
  {
    id: '8', name: '3~4房',
  },
  {
    id: '9', name: '4~5房',
  },
  {
    id: '10', name: '6房以上',
  },
];
const houseTradeParams = [

  {
    id:'1',name:'出售',select:false,
  },
  {
    id: '2', name: '出租',select:false,
  },
  {
    id: '3', name: '租售',select:false,
  }
];

const houseTradeParamsType = [

  {
    id:'1',name:'新房',select:false,
  },
  {
    id: '2', name: '二手房',select:false,
  },

];

const houseTypeParams = [
  {
    id:'售价降',name:'售价降',select:false,
  },
  {
    id:'售价涨',name:'售价涨',select:false,
  },
  {
    id:'售价修改',name:'售价修改',select:false,
  },
  {
    id:'租价降',name:'租价降',select:false,
  },
  {
    id:'租价涨',name:'租价涨',select:false,
  },
  {
    id:'租价修改',name:'租价修改',select:false,
  },
  {
    id:'封盘',name:'封盘',select:false,
  },
  {
    id:'特盘',name:'特盘',select:false,
  },
  {
    id:'私盘',name:'私盘',select:false,
  },
  
  {
    id:'状态修改',name:'状态修改',select:false,
  },
  {
    id:'有效',name:'有效',select:false,
  },
  {
    id:'预定',name:'预定',select:false,
  },
  {
    id:'我售',name:'我售',select:false,
  },
  {
    id:'已售',name:'已售',select:false,
  },
  {
    id:'我租',name:'我租',select:false,
  },
  {
    id:'已租',name:'已租',select:false,
  },
  {
    id:'暂缓',name:'暂缓',select:false,
  },
  {
    id:'未知',name:'未知',select:false,
  },
  {
    id:'无效',name:'无效',select:false,
  }
];

const dataParams = [
  {
    id:'1',name:'超过1天',select:false,
  },
  {
    id:'2',name:'超过2天',select:false,
  },
  {
    id:'3',name:'超过3天',select:false,
  },
  {
    id:'4',name:'超过4天',select:false,
  },
  {
    id:'5',name:'超过5天',select:false,
  },
  {
    id:'6',name:'超过6天',select:false,
  },
  {
    id:'7',name:'超过7天',select:false,
  },
  {
    id:'8',name:'超过8天',select:false,
  },
  {
    id:'9',name:'超过9天',select:false,
  },
  {
    id:'10',name:'超过10天',select:false,
  },
  {
    id:'11',name:'超过11天',select:false,
  },
  {
    id:'12',name:'超过12天',select:false,
  },
  {
    id:'13',name:'超过13天',select:false,
  },
  {
    id:'14',name:'超过14天',select:false,
  },
  {
    id:'15',name:'超过15天',select:false,
  },
  {
    id:'16',name:'超过16天',select:false,
  },
  {
    id:'17',name:'超过17天',select:false,
  },
  {
    id:'18',name:'超过18天',select:false,
  },
  {
    id:'19',name:'超过19天',select:false,
  },
  {
    id:'20',name:'超过10天',select:false,
  },
  {
    id:'30',name:'超过1个月',select:false,
  },
  {
    id:'60',name:'超过2个月',select:false,
  },
  {
    id:'90',name:'超过3个月',select:false,
  },
  {
    id:'180',name:'超过6个月',select:false,
  },
];

const rentColumn = [
  {
    id:2019121901,
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'√',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121902,
    type:'',
    width:'40',
    ref:'',
    prop:'icon',
    label:'!',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },

  {
    id:2019121903,
    type:'',
    width:'110',
    ref:'',
    prop:'roomCode',
    label:'编号',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },

  {
    id:2019121904,
    type:'',
    width:'80',
    ref:'',
    prop:'district',
    label:'区县',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',

  },
  {
    id:2019121905,
    type:'',
    width:'120',
    ref:'',
    prop:'street',
    label:'街镇',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121906,
    type:'',
    width:'200',
    ref:'',
    prop:'adress',
    label:'地址',
    sortable:true,
    show:true,
    fixed:false,
    align:'left',
  },
  {
    id:2019121907,
    type:'',
    width:'80',
    ref:'',
    prop:'roomShape',
    label:'房型',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121908,
    type:'',
    width:'50',
    ref:'',
    prop:'roomDirection',
    label:'朝向',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },

  {
    id:2019121909,
    type:'',
    width:'65',
    ref:'',
    prop:'num',
    label:'自定号',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121910,
    type:'',
    width:'60',
    ref:'',
    prop:'roomTotalArea',
    label:'面积',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121911,
    type:'',
    width:'80',
    ref:'',
    prop:'source',
    label:'来源',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121912,
    type:'',
    width:'50',
    ref:'',
    prop:'roomType',
    label:'交易',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121913,
    type:'',
    width:'50',
    ref:'',
    prop:'roomSaleState',
    label:'状态',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121914,
    type:'',
    width:'50',
    ref:'',
    prop:'roomProperty1',
    label:'盘制',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121915,
    type:'',
    width:'80',
    ref:'',
    prop:'roomProperty2',
    label:'分类',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121916,
    type:'',
    width:'80',
    ref:'',
    prop:'roomProperty3',
    label:'委托方式',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121917,
    type:'',
    width:'80',
    ref:'',
    prop:'roomDelegateDate',
    label:'委托日期',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121918,
    type:'',
    width:'170',
    ref:'',
    prop:'salePrice',
    label:'售价',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
    sortMethod:function(a,b) {
      return (Number(a.salePrice.replace('万元','')) - Number(b.salePrice.replace('万元','')))
    }
  },
  {
    id:2019121919,
    type:'',
    width:'170',
    ref:'',
    prop:'rentPrice',
    label:'租价',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121920,
    type:'',
    width:'80',
    ref:'',
    prop:'roomTaxTypeId',
    label:'税费类型',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121921,
    type:'',
    width:'80',
    ref:'',
    prop:'restPrice',
    label:'尾款',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121922,
    type:'',
    width:'80',
    ref:'',
    prop:'motive',
    label:'动机',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },

  {
    id:2019121923,
    type:'',
    width:'80',
    ref:'',
    prop:'certificateType',
    label:'证件',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121924,
    type:'',
    width:'120',
    ref:'',
    prop:'roomState',
    label:'现状',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121925,
    type:'',
    width:'80',
    ref:'',
    prop:'decorate',
    label:'装修',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121926,
    type:'',
    width:'80',
    ref:'',
    prop:'keysName',
    label:'看房',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121927,
    type:'',
    width:'80',
    ref:'',
    prop:'houseProperty',
    label:'产权',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121928,
    type:'',
    width:'80',
    ref:'',
    prop:'payment',
    label:'付款',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121929,
    type:'',
    width:'80',
    ref:'',
    prop:'commission',
    label:'付佣',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121930,
    type:'',
    width:'130',
    ref:'',
    prop:'emp1',
    label:'员工1',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:2019121931,
    type:'',
    width:'130',
    ref:'',
    prop:'emp2',
    label:'员工2',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121932,
    type:'',
    width:'130',
    ref:'',
    prop:'emp3',
    label:'员工3',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  },
  {
    id:2019121933,
    type:'',
    width:'130',
    ref:'',
    prop:'processingTime',
    label:'最后跟进日',
    sortable:true,
    show:false,
    fixed:false,
    align:'center',
  }
];
const followColumn = [
  {
    id:"2019121901",
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'√',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121902",
    type:'',
    width:'130',
    ref:'',
    prop:'createTime',
    label:'跟进时间',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121903",
    type:'',
    width:'75',
    ref:'',
    prop:'processWayId',
    label:'方式',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121904",
    type:'',
    width:'200',
    ref:'',
    prop:'remark',
    label:'跟进内容',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121905",
    type:'',
    width:'130',
    ref:'',
    prop:'emp',
    label:'跟进人',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121906",
    type:'',
    width:'90',
    ref:'',
    prop:'roomCode',
    label:'房源编号',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121907",
    type:'',
    width:'120',
    ref:'',
    prop:'areaVillage',
    label:'楼盘字典',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121908",
    type:'',
    width:'110',
    ref:'',
    prop:'seat',
    label:'栋座位置',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"20191219009",
    type:'',
    width:'70',
    ref:'',
    prop:'roomId',
    label:'房号',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121912",
    type:'',
    width:'140',
    ref:'',
    prop:'cusname',
    label:'客户',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121910",
    type:'',
    width:'70',
    ref:'',
    prop:'roomType',
    label:'交易',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121911",
    type:'',
    width:'70',
    ref:'',
    prop:'roomSaleStateId',
    label:'状态',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
];
const keyColumn = [
  {
    id:"2019121901",
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'√',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121902",
    type:'',
    width:'180',
    ref:'',
    prop:'areaVillage',
    label:'地址',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121903",
    type:'',
    width:'75',
    ref:'',
    prop:'roomSaleStateId',
    label:'房源状态',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },

  {
    id:"2019121904",
    type:'',
    width:'75',
    ref:'',
    prop:'keyTypeId',
    label:'类型',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121905",
    type:'',
    width:'150',
    ref:'',
    prop:'emp',
    label:'钥匙负责人',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121906",
    type:'',
    width:'70',
    ref:'',
    prop:'state',
    label:'状态',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121907",
    type:'',
    width:'100',
    ref:'',
    prop:'lender1',
    label:'外借人',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121908",
    type:'',
    width:'110',
    ref:'',
    prop:'lendDate1',
    label:'外借日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121909",
    type:'',
    width:'100',
    ref:'',
    prop:'lender4',
    label:'内借人',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"20191219010",
    type:'',
    width:'110',
    ref:'',
    prop:'lendDate4',
    label:'内借日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"20191219011",
    type:'',
    width:'100',
    ref:'',
    prop:'lender2',
    label:'收回人',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121912",
    type:'',
    width:'110',
    ref:'',
    prop:'lendDate2',
    label:'收回日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121913",
    type:'',
    width:'100',
    ref:'',
    prop:'lender3',
    label:'归还人',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
  {
    id:"2019121914",
    type:'',
    width:'110',
    ref:'',
    prop:'lendDate3',
    label:'归还日',
    sortable:true,
    show:true,
    fixed:false,
    align:'center',
  },
];
export const rentConstParam = {
    rentColumn:rentColumn,
    followColumn:followColumn,
    keyColumn:keyColumn,
    houses:houseArr,
    premisesParams:premisesArr,
    yearParams:yearArr,
    salePriceParams:salePriceParams,
    rentPriceParams:rentPriceParams,
    houseParams1:houseParams1,
    houseTradeParams:houseTradeParams,
    houseTradeParamsType:houseTradeParamsType,
    houseTypeParams:houseTypeParams,
    dataParams:dataParams,
    houseShapeType:houseShapeType,
}
