const repColumn = [
  {
    id:20192201,
    type:'selection',
    width:'30',
    ref:'multipleTable',
    prop:'check',
    label:'√',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192202,
    type:'',
    width:'120',
    ref:'',
    prop:'projectName',
    label:'项目名称',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192203,
    type:'',
    width:'120',
    ref:'',
    prop:'customerName',
    label:'客户名称',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192204,
    type:'',
    width:'100',
    ref:'',
    prop:'customerPhone',
    label:'客户手机',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192205,
    type:'',
    width:'200',
    ref:'',
    prop:'customerCard',
    label:'身份证号',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
 
  {
    id:20192207,
    type:'',
    width:'80',
    ref:'',
    prop:'platformEmpName2',
    label:'平台人员',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },

  {
    id:20192208,
    type:'',
    width:'100',
    ref:'',
    prop:'platformEmpPhone',
    label:'平台人电话',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },

  {
    id:20192210,
    type:'',
    width:'200',
    ref:'',
    prop:'delegateEmpName2',
    label:'销售人员',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },

  {
    id:20192211,
    type:'',
    width:'120',
    ref:'',
    prop:'delegateEmpPhone',
    label:'销售人电话',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },

  {
    id:20192212,
    type:'',
    width:'200',
    ref:'',
    prop:'reportPerson',
    label:'报备人员',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192213,
    type:'',
    width:'100',
    ref:'',
    prop:'reportPersonPhone',
    label:'报备电话',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192214,
    type:'',
    width:'115',
    ref:'',
    prop:'reportDays',
    label:'报备截止时间',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192215,
    type:'',
    width:'115',
    ref:'',
    prop:'arriveDays',
    label:'到场截止时间',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:201922132332,
    type:'',
    width:'70',
    ref:'',
    prop:'card',
    label:'排卡状态',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:2019221323324,
    type:'',
    width:'140',
    ref:'',
    prop:'cardDate',
    label:'排卡剩余（状态）',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:2019221322,
    type:'',
    width:'115',
    ref:'',
    prop:'openDate',
    label:'开盘',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  
  {
    id:20192216,
    type:'',
    width:'80',
    ref:'',
    prop:'reportNum',
    label:'报备编号',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192217,
    type:'',
    width:'80',
    ref:'',
    prop:'reportState',
    label:'报备状态',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  
  
  
  
 
  {
    id:20192218,
    type:'',
    width:'140',
    ref:'',
    prop:'reportDate',
    label:'报备时间',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192219,
    type:'',
    width:'200',
    ref:'',
    prop:'remark',
    label:'报备备注',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20192220,
    type:'',
    width:'80',
    ref:'',
    prop:'num',
    label:'带看次数',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },

];

export const reportparames = {
  repColumn: repColumn,
}
