const rewardList = [
    {
      id:"202022401",
      type:'selection',
      width:'30',
      ref:'multipleTable',
      prop:'check',
      label:'√',
      sortable:true,
      show:true,
      fixed:false,
      align:'center',
    },
    {
      id:"202022402",
      type:'',
      width:'130',
      ref:'',
      prop:'time',
      label:'奖罚年月',
      sortable:true,
      show:true,
      fixed:false,
      align:'center',
    },
    {
      id:"202022403",
      type:'',
      width:'150',
      ref:'',
      prop:'user',
      label:'奖罚人员',
      sortable:true,
      show:true,
      fixed:false,
      align:'center',
    },
    {
      id:"202022404",
      type:'',
      width:'80',
      ref:'',
      prop:'state',
      label:'人员状态',
      sortable:true,
      show:false,
      fixed:false,
      align:'center',
    },
    {
      id:"202022405",
      type:'',
      width:'80',
      ref:'',
      prop:'staffId',
      label:'职位',
      sortable:true,
      show:false,
      fixed:false,
      align:'center',
    },
    {
      id:"202022406",
      type:'',
      width:'100',
      ref:'',
      prop:'type',
      label:'奖罚',
      sortable:true,
      show:true,
      fixed:false,
      align:'center',
    },
    // {
    //   id:"202022407",
    //   type:'',
    //   width:'100',
    //   ref:'',
    //   prop:'typeParam',
    //   label:'单项',
    //   sortable:true,
    //   show:true,
    //   fixed:false,
    //   align:'center',
    // },
    {
      id:"202022408",
      type:'',
      width:'90',
      ref:'',
      prop:'punishNum',
      label:'奖罚金额',
      sortable:true,
      show:true,
      fixed:false,
      align:'center',
    },
    {
      id:"202022409",
      type:'',
      width:'120',
      ref:'',
      prop:'punishReason',
      label:'奖罚备注',
      sortable:true,
      show:true,
      fixed:false,
      align:'center',
    },
    {
      id:"20202210",
      type:'',
      width:'110',
      ref:'',
      prop:'createBy',
      label:'提交人',
      sortable:true,
      show:true,
      fixed:false,
      align:'center',
    },
    {
      id:"202022411",
      type:'',
      width:'150',
      ref:'',
      prop:'createTime',
      label:'提交日期',
      sortable:true,
      show:true,
      fixed:false,
      align:'center',
    }
      
  ];

  export const rewardParam = {
    rewardList: rewardList,

  };
  