const takeLookparam = [
  {
    id:20190101,
    type:'selection',
    width:'50',
    ref:'multipleTable',
    prop:'check',
    label:'',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190102,
    type:'',
    width:'120',
    ref:'',
    prop:'date',
    label:'带看时间',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190103,
    type:'',
    width:'50',
    ref:'',
    prop:'look',
    label:'方式',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190104,
    type:'',
    width:'120',
    ref:'',
    prop:'person',
    label:'带看人',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190105,
    type:'',
    width:'140',
    ref:'',
    prop:'remark',
    label:'带看内容',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190106,
    type:'',
    width:'80',
    ref:'',
    prop:'procode',
    label:'项目编号',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190107,
    type:'',
    width:'130',
    ref:'',
    prop:'proname',
    label:'带看项目',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190108,
    type:'',
    width:'130',
    ref:'',
    prop:'cusname',
    label:'客户',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190109,
    type:'',
    width:'80',
    ref:'',
    prop:'prstate',
    label:'营销状态',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
  {
    id:20190110,
    type:'',
    width:'80',
    ref:'',
    prop:'costate',
    label:'合作状态',
    align:'center',
    sortable:true,
    show:true,
    fixed:false
  },
];

export const takeLookparams = {
  takeLookparam: takeLookparam,
}
